version: '3.1'

networks:
  sb_net:
    driver: bridge

services:

  postgres:
    image: debezium/postgres:12
    hostname: postgres
    container_name: postgres-demo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-pw
      POSTGRES_DB: hust_blog
    volumes:
      - ./postgres/custom-config.conf:/etc/postgresql/postgresql.conf
    networks:
      - sb_net
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: api-demo
#    environment:
#      DB_HOST: postgres
#      KAFKA_HOST: kafka:9092
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#      - kafka
#    networks:
#      - sb_net
#
#
#
#  elastic:
#    image: elasticsearch:7.6.2
#    hostname: elastic
#    container_name: elastic-demo
#    networks:
#      - sb_net
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      discovery.type: single-node
